### ISSUE TITLE
funannotate setup failure

### ISSUE THREAD

**Issue by liulu0827** [nextgenusfs/funannotate#434]
I installed funannotate using these commands:

conda create -n funannotate python=2.7 funannotate
conda activate funannotate
funannotate check --show-versions
export GENEMARK_PATH=/home/liulu/funannotate/gmes_linux_64
export FUNANNOTATE_DB=/home/liulu/funannotate/funannotate_db
funannotate setup -d /home/liulu/funannotate/funannotate_db

I passed funannotate check:
-------------------------------------------------------
Checking dependencies for 1.7.4
-------------------------------------------------------
You are running Python v 2.7.15. Now checking python packages...
biopython: 1.76
goatools: 1.0.5
matplotlib: 2.2.4
natsort: 6.2.0
numpy: 1.16.5
pandas: 0.24.2
psutil: 5.7.0
requests: 2.23.0
scikit-learn: 0.20.3
scipy: 1.2.1
seaborn: 0.9.0
All 11 python packages installed

You are running Perl v 5.026002. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed

Checking Environmental Variables...
$FUNANNOTATE_DB=/home/liulu/funannotate/funannotate_db
$PASAHOME=/home/liulu/miniconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/liulu/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/liulu/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/liulu/miniconda3/envs/funannotate/config/
$GENEMARK_PATH=/home/liulu/funannotate/gmes_linux_64
All 6 environmental variables are set
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
emapper.py: 2.0.1-14-gbf04860
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
gmes_petap.pl: 4.58_lic
hisat2: 2.2.0
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.467 (2020/May/14)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.16
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.9
signalp: 4.1
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
All 36 external dependencies are installed

But when I  tried to setup funannotate_db using 
"funannotate setup -d /home/liulu/funannotate/funannotate_db", 
I got this error:

[10:36 AM]: OS: linux2, 48 cores, ~ 197 GB RAM. Python: 2.7.15
[10:36 AM]: Running 1.7.4
[10:36 AM]: Database location: /home/liulu/funannotate/funannotate_db
[10:36 AM]: Parsing Augustus pre-trained species and porting to funannotate
**Traceback (most recent call last):
  File "/home/liulu/miniconda3/envs/funannotate/bin/funannotate", line 660, in <module>
    main()
  File "/home/liulu/miniconda3/envs/funannotate/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/home/liulu/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 652, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/liulu/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 132, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: 'NoneType' object is not iterable**

I am confused with this error, is there anything wrong with my installation. How can I solve this problem.

Thank you for your attention.

**Comment by nextgenusfs** [comment]
Perhaps the merops database is down -- can you specify one of the other databases only during setup to see if they download/install correctly?  I think that Pfam link might be dead as well as of today #433

**Comment by mswyers** [comment]
Hey Jon,

Attempting a new install on a machine and I'm getting this same error on the funannotate setup. I switched over to the master pip install (1.8.0) and it didn't fix it.

``` (funannotate) mswyers@Michael-PC:~$ funannotate check
-------------------------------------------------------
Checking dependencies for 1.8.0
-------------------------------------------------------
To print all dependencies and versions: funannotate check --show-versions

You are running Python v 2.7.15. Now checking python packages...
All 11 python packages installed


You are running Perl v 5.026002. Now checking perl modules...
All 27 Perl modules installed


Checking Environmental Variables...
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
        ERROR: gmes_petap.pl not installed
        ERROR: signalp not installed
```

```
[10:30 AM]: OS: linux2, 8 cores, ~ 34 GB RAM. Python: 2.7.15
[10:30 AM]: Running 1.8.0
[10:30 AM]: Database location: /home/mswyers/funannotate_db
[10:30 AM]: Retrieving download links from GitHub Repo
[10:30 AM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/home/mswyers/miniconda3/envs/funannotate/bin/funannotate", line 668, in <module>
    main()
  File "/home/mswyers/miniconda3/envs/funannotate/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/home/mswyers/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 686, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/mswyers/miniconda3/envs/funannotate/lib/python2.7/site-packages/funannotate/setupDB.py", line 139, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: 'NoneType' object is not iterable
```

**Comment by mswyers** [comment]
Also a note, I'm able to download files from the merops database manually so it's not that the database isn't working.

**Comment by nextgenusfs** [comment]
Install the latest and should be fixed -- I just haven't had a chance to tag a new release and build conda image yet.....
```
#make sure you are in env
conda activate funannotate

python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```
And then re-run setup.

**Comment by mswyers** [comment]
Going to a fresh env, installing deps from conda, swapping python versions, and then running the above script so it build correctly and I still get the same error on running setup:

``` 
(funannotate) mswyers@Michael-PC:~$ funannotate check --show-versions
-------------------------------------------------------
Checking dependencies for 1.8.0
-------------------------------------------------------
You are running Python v 3.6.11. Now checking python packages...
biopython: 1.77
goatools: 1.0.6
matplotlib: 3.3.0
natsort: 7.0.1
numpy: 1.19.1
pandas: 1.1.0
psutil: 5.7.2
requests: 2.24.0
scikit-learn: 0.23.2
scipy: 1.5.2
seaborn: 0.10.1
All 11 python packages installed


You are running Perl v b'5.026002'. Now checking perl modules...
Bio::Perl: 1.007002
Carp: 1.38
Clone: 0.42
DBD::SQLite: 1.64
DBD::mysql: 4.046
DBI: 1.642
DB_File: 1.852
Data::Dumper: 2.173
File::Basename: 2.85
File::Which: 1.23
Getopt::Long: 2.5
Hash::Merge: 0.300
JSON: 4.02
LWP::UserAgent: 6.39
Logger::Simple: 2.0
POSIX: 1.76
Parallel::ForkManager: 2.02
Pod::Usage: 1.69
Scalar::Util::Numeric: 0.40
Storable: 3.15
Text::Soundex: 3.05
Thread::Queue: 3.12
Tie::File: 1.02
URI::Escape: 3.31
YAML: 1.29
threads: 2.15
threads::shared: 1.56
All 27 Perl modules installed


Checking Environmental Variables...
$FUNANNOTATE_DB=/home/mswyers/funannotate_db
$PASAHOME=/home/mswyers/miniconda3/envs/funannotate/opt/pasa-2.4.1
$TRINITY_HOME=/home/mswyers/miniconda3/envs/funannotate/opt/trinity-2.8.5
$EVM_HOME=/home/mswyers/miniconda3/envs/funannotate/opt/evidencemodeler-1.1.1
$AUGUSTUS_CONFIG_PATH=/home/mswyers/miniconda3/envs/funannotate/config/
        ERROR: GENEMARK_PATH not set. export GENEMARK_PATH=/path/to/dir
-------------------------------------------------------
Checking external dependencies...
PASA: 2.4.1
CodingQuarry: 2.0
Trinity: 2.8.5
augustus: 3.3.3
bamtools: bamtools 2.5.1
bedtools: bedtools v2.29.2
blat: BLAT v36
diamond: 0.9.21
ete3: 3.1.1
exonerate: exonerate 2.4.0
fasta: no way to determine
glimmerhmm: 3.0.4
gmap: 2017-11-15
hmmscan: HMMER 3.3 (Nov 2019)
hmmsearch: HMMER 3.3 (Nov 2019)
java: 11.0.1-internal
kallisto: 0.46.2
mafft: v7.471 (2020/Jul/3)
makeblastdb: makeblastdb 2.2.31+
minimap2: 2.17-r941
proteinortho: 6.0.18
pslCDnaFilter: no way to determine
salmon: salmon 0.14.1
samtools: samtools 1.7
snap: 2006-07-28
stringtie: 2.1.2
tRNAscan-SE: 2.0.5 (October 2019)
tantan: tantan 13
tbl2asn: no way to determine, likely 25.X
tblastn: tblastn 2.2.31+
trimal: trimAl v1.4.rev15 build[2013-12-17]
trimmomatic: 0.39
        ERROR: emapper.py not installed
        ERROR: gmes_petap.pl not installed
        ERROR: hisat2 not installed
        ERROR: signalp not installed
(funannotate) mswyers@Michael-PC:~$ funannotate setup -i all -d ~/funannotate_db
-------------------------------------------------------
[12:27 PM]: OS: debian buster/sid, 8 cores, ~ 34 GB RAM. Python: 3.6.11
[12:27 PM]: Running 1.8.0
[12:27 PM]: Database location: /home/mswyers/funannotate_db
[12:27 PM]: Retrieving download links from GitHub Repo
[12:27 PM]: Parsing Augustus pre-trained species and porting to funannotate
Traceback (most recent call last):
  File "/home/mswyers/miniconda3/envs/funannotate/bin/funannotate", line 668, in <module>
    main()
  File "/home/mswyers/miniconda3/envs/funannotate/bin/funannotate", line 658, in main
    mod.main(arguments)
  File "/home/mswyers/miniconda3/envs/funannotate/lib/python3.6/site-packages/funannotate/setupDB.py", line 686, in main
    meropsDB(DatabaseInfo, args.force, args=args)
  File "/home/mswyers/miniconda3/envs/funannotate/lib/python3.6/site-packages/funannotate/setupDB.py", line 139, in meropsDB
    type, name, version, date, records, checksum = info.get('merops')
TypeError: 'NoneType' object is not iterable
```

**Comment by nextgenusfs** [comment]
Hmmm... I don't know, just ran this:
```
$ funannotate setup -i merops --force
-------------------------------------------------------
[Aug 05 10:33 AM]: OS: MacOSX 10.14.6, 8 cores, ~ 17 GB RAM. Python: 3.7.6
[Aug 05 10:33 AM]: Running 1.8.0
[Aug 05 10:33 AM]: Database location: /usr/local/share/funannotate
[Aug 05 10:33 AM]: Retrieving download links from GitHub Repo
[Aug 05 10:33 AM]: Parsing Augustus pre-trained species and porting to funannotate
[Aug 05 10:33 AM]: Downloading Merops database
[Aug 05 10:33 AM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1957603
[Aug 05 10:33 AM]: Building diamond database
[Aug 05 10:33 AM]: MEROPS Database: version=12.0 date=2017-10-04 records=5,009
```

Can you install the other ftp resources, ie UniProt?
```
$ funannotate setup -i UniProt --force
```
If you can't, then its most likely a local setting you have with an ftp proxy.  You can try to use wget, by passing the `-w` flag to funannotate setup, on most systems `wget` is more easy to configure for proxy settings than the python requests module.

**Comment by mswyers** [comment]
Actually, passing the --force option seems to work. That's really strange.

On my main machine, this all works just fine without having to update to the master.

So the problem is some kind of local ftp settings then?

**Comment by nextgenusfs** [comment]
Not if it worked with just `--force`.  Might be something else related to existing installation -- you could test by just passing a new path to `-d` without using `--force` and see if in a clean directory it works and fails in an existing directory.  If that's the case, then I need to fix something....

**Comment by mswyers** [comment]
It worked without the --force by passing to a new directory:

```
(funannotate) mswyers@Michael-PC:~$ funannotate setup -i all -d /home/mswyers/test2
-------------------------------------------------------
[12:44 PM]: OS: debian buster/sid, 8 cores, ~ 34 GB RAM. Python: 3.6.11
[12:44 PM]: Running 1.8.0
[12:44 PM]: Database location: /home/mswyers/test2
[12:44 PM]: Retrieving download links from GitHub Repo
[12:44 PM]: Parsing Augustus pre-trained species and porting to funannotate
[12:44 PM]: Downloading Merops database
[12:44 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/merops/current_release/merops_scan.lib Bytes: 1957603
[12:44 PM]: Building diamond database
[12:44 PM]: MEROPS Database: version=12.0 date=2017-10-04 records=5,009
[12:44 PM]: Downloading UniProtKB/SwissProt database
[12:44 PM]: Downloading: ftp://ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz Bytes: 89387983
64733184  [72.42%]

```

**Comment by nextgenusfs** [comment]
Ok thanks -- I'll see if I can figure out why.

**Comment by nextgenusfs** [comment]
But if you could also run it again over the top of that /home/mswers/test2 directory and validate that it failed again that would be helpful.  It also could have been a partial download/fail that caused the problem, thus `--force` fixed it?

**Comment by mswyers** [comment]
Strangely enough the error isn't reproduced by doing this.....

What DOES reproduce the error is if something interrupts the setup mid-run and you try to re-run the process. This may be the actual problem. Fix seems to be just deleting the database folder and running setup again.

**Comment by nextgenusfs** [comment]
Yeah okay, thanks.  Probably just a partial then and something amiss -- so deleting whole folder and starting over is okay.  Its probably the text file that gets written for each database, my guess would be that its empty and that's the error.  I can maybe look at capturing that error, but I don't view as a huge problem?

**Comment by mswyers** [comment]
No I don't think it's a huge issue, as it's a pretty easy fix and something you'd expect people to try as a solution by default anyways.

Also shouldn't really occur regularly anyways.

Thanks for the help with this!

**Comment by ScientistJake** [comment]
Hi all,
I was having similar issues. @nextgenusfs fix worked:
```
conda activate funannotate
python -m pip install git+https://github.com/nextgenusfs/funannotate.git
```
