### ISSUE TITLE
UnboundLocalError: local variable 'AUGUSTUS_BASE' referenced before assignment

### ISSUE THREAD

**Issue by DiegoSafian** [nextgenusfs/funannotate#850]
**Are you using the latest release?**
If you are not using the latest release of funannotate, please upgrade, if bug persists then report here.

**Describe the bug**
The training with Augustus is failing becouse UnboundLocalError: local variable 'AUGUSTUS_BASE' referenced before assignment

**What command did you issue?**
funannotate predict --species p_turneri_fun \
--input turneri_genome.fasta \
--out turneri_test \
--transcript_evidence /camp/home/safiand/home/users/safiand/Bulk.rna_poeciliidae/turneri/trinity_out_dir/Trinity-GG.fasta \
--rna_bam /camp/home/safiand/home/users/safiand/genome_annotation/turneri/rna_protein_turneri/RNA_alignmentAligned.sortedByCoord.out.bam \
--protein_evidence /camp/home/safiand/home/users/safiand/genome_annotation/protein_pociliidae_ensambl/proteinsfishes.fasta \
--genemark_gtf /camp/home/safiand/home/users/safiand/genome_annotation/turneri/rna_protein_turneri/braker/prote_rna_turneri/GeneMark-ETP/genemark.gtf \
--busco_db actinopterygii \
--organism other \
--max_intronlen 100000 \
--optimize_augustus \
--repeats2evm \
--cpus 32 \
--force \
--AUGUSTUS_CONFIG_PATH=/camp/home/safiand/home/users/safiand/bin/augustus_config_system \
--GENEMARK_PATH=/camp/home/safiand/home/users/safiand/bin/gmes_linux_64_mod 

**Logfiles**
Traceback (most recent call last):
  File "/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/bin/funannotate", line 10, in <module>
    sys.exit(main())
  File "/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/funannotate.py", line 716, in main
    mod.main(arguments)
  File "/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/predict.py", line 1415, in main
    lib.trainAugustus(AUGUSTUS_BASE, aug_species, trainingset,
UnboundLocalError: local variable 'AUGUSTUS_BASE' referenced before assignment

**OS/Install Information**
 -  output of `funannotate check --show-versions`
At the moment cannot present this because I am re-installing using conda. But Augustus v is 3.5

**Comment by DiegoSafian** [comment]
It appears there is a problem with Augustus.

Running `funannotate predict` unit testing
Downloading: https://osf.io/te2pf/download?version=1 Bytes: 1489808
8192  [0.55%]16384  [1.10%]24576  [1.65%]32768  [2.20%]40960  [2.75%]49152  [3.30%]57344  [3.85%]65536  [4.40%]73728  [4.95%]81920  [5.50%]90112  [6.05%]98304  [6.60%]106496  [7.15%]114688  [7.70%]122880  [8.25%]131072  [8.80%]139264  [9.35%]147456  [9.90%]155648  [10.45%]163840  [11.00%]172032  [11.55%]180224  [12.10%]188416  [12.65%]196608  [13.20%]204800  [13.75%]212992  [14.30%]221184  [14.85%]229376  [15.40%]237568  [15.95%]245760  [16.50%]253952  [17.05%]262144  [17.60%]270336  [18.15%]278528  [18.70%]286720  [19.25%]294912  [19.80%]303104  [20.35%]311296  [20.90%]319488  [21.44%]327680  [21.99%]335872  [22.54%]344064  [23.09%]352256  [23.64%]360448  [24.19%]368640  [24.74%]376832  [25.29%]385024  [25.84%]393216  [26.39%]401408  [26.94%]409600  [27.49%]417792  [28.04%]425984  [28.59%]434176  [29.14%]442368  [29.69%]450560  [30.24%]458752  [30.79%]466944  [31.34%]475136  [31.89%]483328  [32.44%]491520  [32.99%]499712  [33.54%]507904  [34.09%]516096  [34.64%]524288  [35.19%]532480  [35.74%]540672  [36.29%]548864  [36.84%]557056  [37.39%]565248  [37.94%]573440  [38.49%]581632  [39.04%]589824  [39.59%]598016  [40.14%]606208  [40.69%]614400  [41.24%]622592  [41.79%]630784  [42.34%]638976  [42.89%]647168  [43.44%]655360  [43.99%]663552  [44.54%]671744  [45.09%]679936  [45.64%]688128  [46.19%]696320  [46.74%]704512  [47.29%]712704  [47.84%]720896  [48.39%]729088  [48.94%]737280  [49.49%]745472  [50.04%]753664  [50.59%]761856  [51.14%]770048  [51.69%]778240  [52.24%]786432  [52.79%]794624  [53.34%]802816  [53.89%]811008  [54.44%]819200  [54.99%]827392  [55.54%]835584  [56.09%]843776  [56.64%]851968  [57.19%]860160  [57.74%]868352  [58.29%]876544  [58.84%]884736  [59.39%]892928  [59.94%]901120  [60.49%]909312  [61.04%]917504  [61.59%]925696  [62.14%]933888  [62.69%]942080  [63.23%]950272  [63.78%]958464  [64.33%]966656  [64.88%]974848  [65.43%]983040  [65.98%]991232  [66.53%]999424  [67.08%]1007616  [67.63%]1015808  [68.18%]1024000  [68.73%]1032192  [69.28%]1040384  [69.83%]1048576  [70.38%]1056768  [70.93%]1064960  [71.48%]1073152  [72.03%]1081344  [72.58%]1089536  [73.13%]1097728  [73.68%]1105920  [74.23%]1114112  [74.78%]1122304  [75.33%]1130496  [75.88%]1138688  [76.43%]1146880  [76.98%]1155072  [77.53%]1163264  [78.08%]1171456  [78.63%]1179648  [79.18%]1187840  [79.73%]1196032  [80.28%]1204224  [80.83%]1212416  [81.38%]1220608  [81.93%]1228800  [82.48%]1236992  [83.03%]1245184  [83.58%]1253376  [84.13%]1261568  [84.68%]1269760  [85.23%]1277952  [85.78%]1286144  [86.33%]1294336  [86.88%]1302528  [87.43%]1310720  [87.98%]1318912  [88.53%]1327104  [89.08%]1335296  [89.63%]1343488  [90.18%]1351680  [90.73%]1359872  [91.28%]1368064  [91.83%]1376256  [92.38%]1384448  [92.93%]1392640  [93.48%]1400832  [94.03%]1409024  [94.58%]1417216  [95.13%]1425408  [95.68%]1433600  [96.23%]1441792  [96.78%]1449984  [97.33%]1458176  [97.88%]1466368  [98.43%]1474560  [98.98%]1482752  [99.53%]1489808  [100.00%]-------------------------------------------------------
[Dec 31 09:33 AM]: OS: CentOS Linux 7, 32 cores, ~ 263 GB RAM. Python: 3.8.15
[Dec 31 09:33 AM]: Running funannotate v1.8.13
[Dec 31 09:33 AM]: GeneMark not found and $GENEMARK_PATH environmental variable missing. Will skip GeneMark ab-initio prediction.
[Dec 31 09:33 AM]: Skipping CodingQuarry as no --rna_bam passed
[Dec 31 09:33 AM]: Parsed training data, run ab-initio gene predictors as follows:
  [4mProgram      Training-Method[0m
  augustus     pretrained     
  glimmerhmm   busco          
  snap         busco          
[Dec 31 09:33 AM]: Loading genome assembly and parsing soft-masked repetitive sequences
[Dec 31 09:33 AM]: Genome loaded: 6 scaffolds; 3,776,588 bp; 19.75% repeats masked
[Dec 31 09:33 AM]: Mapping 1,065 proteins to genome using diamond and exonerate
[Dec 31 09:33 AM]: Found 1,505 preliminary alignments with diamond in 0:00:01 --> generated FASTA files for exonerate in 0:00:00
     Progress: 0.00% 
     Progress: 10.63% 
     Progress: 30.70% 
     Progress: 49.50% 
     Progress: 67.51% 
     Progress: 85.25% 
     Progress: 99.87% 
     Progress: 99.93% 
     Progress: 99.93% 
     Progress: 99.93% 
     Progress: 99.93% 
     Progress: 99.93% 
[Dec 31 09:34 AM]: Exonerate finished in 0:00:12: found 1,270 alignments
[Dec 31 09:34 AM]: Running BUSCO to find conserved gene models for training ab-initio predictors
[Dec 31 09:37 AM]: 370 valid BUSCO predictions found, validating protein sequences
[Dec 31 09:38 AM]: 367 BUSCO predictions validated
[Dec 31 09:38 AM]: Running Augustus gene prediction using saccharomyces parameters
     Progress: 0.00% 
[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=1 --predictionEnd=312565.38639533357 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022975.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022974.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=1 --predictionEnd=278016.7473349764 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022970.1.fa
[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022971.1.fa
[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=267676.1293727999 --predictionEnd=545352.2587455998 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022973.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=693683.5714535144 --predictionEnd=1050525.3571802715 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022972.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=346841.7857267572 --predictionEnd=703683.5714535144 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022972.1.fa
[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=1 --predictionEnd=356841.7857267572 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022972.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=302565.38639533357 --predictionEnd=615130.7727906671 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022975.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=268016.7473349764 --predictionEnd=546033.4946699528 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022970.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.


[Dec 31 09:38 AM]: CMD ERROR: augustus --species=saccharomyces --predictionStart=1 --predictionEnd=277676.1293727999 --extrinsicCfgFile=/camp/home/safiand/home/users/safiand/.conda/envs/funannotate/lib/python3.8/site-packages/funannotate/config/extrinsic.E.XNT.RM.cfg --hintsfile=annotate/predict_misc/hints.ALL.gff --AUGUSTUS_CONFIG_PATH=annotate/predict_misc/ab_initio_parameters/augustus --softmasking=1 --gff3=on --UTR=off --stopCodonExcludedFromCDS=False augustus_tmp_e6e201c6-f588-4e19-9593-b2c560ba8f1e/CP022973.1.fa
[Dec 31 09:38 AM]: 
augustus: ERROR
	Could not locate command line parameters file: annotate/predict_misc/ab_initio_parameters/augustus/parameters/aug_cmdln_parameters.json.

**Comment by nextgenusfs** [comment]
I think its because this version of funannotate is not compatible with Augustus v3.5. You can either try to install the latest from the master branch via pip or downgrade Augustus.

**Comment by DiegoSafian** [comment]
Hi Joe,

Thanks for your reply. I followed your advice and updated using python -m pip install git+https://github.com/nextgenusfs/funannotate.git. It seems to work as ausgustus is running fine. I hope the job finishes with no problem. Thanks a lot again for the help and the great Funannotate!

**Comment by max-hence** [comment]
Hi Joe,
I have got the same problem with Augustus.
I'm working on conda env on Linux and either the funannotate predict run never stops either I don't manage to link augustus to Funnanotate. Could you please show me the good version of augustus compatible with funannotate and how to set the environnement ?

Thank you for your help
Max

**Comment by hyphaltip** [comment]
so I did a funannotate install then I forced the downgrade after with
```
mamba install -c bioconda augustus==3.4
```

**Comment by DiegoSafian** [comment]
Hi.,
The problem finally is solved. I just re-install funnanotate using `conda install funannotate` insted of` conda install -c bioconda funannotate` and that make it. Not idea how.

**Comment by hafizmtalha** [comment]
installed funannotate today and still facing the same problem.

> Hi., The problem finally is solved. I just re-installed funnanotate using `conda install funannotate` insted of` conda install -c bioconda funannotate` and that make it. Not idea how.

**Comment by SLAment** [comment]
I seem to have the same issue with Augustus 3.3.3 and Funannotate 1.8.13 :/

**Comment by nextgenusfs** [comment]
I think the latest v1.8.15 should be available on conda as of this morning. It is pinned to augustus v3.5.0, hopefully that solves the frustrating augustus install issues.....
